# Generated by Django 2.0 on 2017-12-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код болезни')),
                ('sex', models.CharField(choices=[('муж', 'муж'), ('жен', 'жен')], default='муж', max_length=5, verbose_name='Пол')),
                ('adult', models.IntegerField(verbose_name='Возраст')),
                ('days', models.IntegerField(verbose_name='Число дней')),
            ],
        ),
    ]
