# Generated by Django 2.0 on 2017-12-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Диапазон возрастов')),
            ],
            options={
                'verbose_name_plural': 'Диапазоны возрастов',
                'verbose_name': 'Диапазон возрастов',
            },
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=120, null=True, verbose_name='Код болезни')),
                ('sex', models.CharField(choices=[('муж', 'муж'), ('жен', 'жен')], default='муж', max_length=5, verbose_name='Пол')),
                ('adult', models.DateField(null=True, verbose_name='Возраст')),
                ('adult_age', models.IntegerField(null=True, verbose_name='Возраст(год)')),
                ('days', models.IntegerField(default=1, verbose_name='Число дней')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('adult_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AgeRange')),
            ],
            options={
                'verbose_name_plural': 'Случаи',
                'ordering': ['-pub_date'],
                'verbose_name': 'Случай',
            },
        ),
        migrations.CreateModel(
            name='Sicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование группы')),
                ('main_group_codes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Коды главной группы')),
            ],
            options={
                'verbose_name_plural': 'Названия группы',
                'verbose_name': 'Название группы',
            },
        ),
        migrations.CreateModel(
            name='SicksSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Код болезни')),
                ('group_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sicks', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Коды болезней',
                'verbose_name': 'Код болезни',
            },
        ),
        migrations.CreateModel(
            name='SicksUndergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование группы')),
                ('group_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sicks')),
            ],
            options={
                'verbose_name_plural': 'Название подгруппы',
                'verbose_name': 'Подгруппы болезни',
            },
        ),
        migrations.AddField(
            model_name='sickssingle',
            name='under_group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksUndergroup', verbose_name='Подгруппа'),
        ),
        migrations.AddField(
            model_name='med',
            name='code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksSingle', verbose_name='Код болезни'),
        ),
        migrations.AddField(
            model_name='med',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
