# Generated by Django 2.0 on 2017-12-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='sex',
            new_name='sexxx',
        ),
    ]
