# Generated by Django 2.0 on 2017-12-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='adult_age',
            field=models.IntegerField(null=True, verbose_name='Возраст(год)'),
        ),
    ]
