# Generated by Django 2.0 on 2017-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicks',
            name='only_sick',
            field=models.BooleanField(default=True, verbose_name='Болезнь'),
        ),
    ]
