# Generated by Django 2.0 on 2017-12-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_med_adult_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование группы')),
            ],
        ),
        migrations.CreateModel(
            name='SicksSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Код болезни')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sicks')),
            ],
        ),
        migrations.CreateModel(
            name='SicksUndergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование группы')),
            ],
        ),
    ]
