# Generated by Django 2.0 on 2017-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171223_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='days',
        ),
        migrations.RemoveField(
            model_name='med',
            name='sexxx',
        ),
        migrations.AddField(
            model_name='med',
            name='sex',
            field=models.CharField(choices=[('муж', 'муж'), ('жен', 'жен')], default='муж', max_length=5, verbose_name='Пол'),
        ),
    ]
