# Generated by Django 2.0 on 2017-12-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sicks_only_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='date_1',
            field=models.DateField(help_text='Период болезни', null=True, verbose_name='С '),
        ),
        migrations.AddField(
            model_name='med',
            name='date_2',
            field=models.DateField(null=True, verbose_name='По'),
        ),
    ]
