# Generated by Django 2.0 on 2017-12-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sicks_sickssingle_sicksundergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickssingle',
            name='group_name',
        ),
        migrations.AddField(
            model_name='sickssingle',
            name='group_name',
            field=models.ManyToManyField(to='main.Sicks'),
        ),
    ]
