# Generated by Django 2.0 on 2017-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171223_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='days',
            field=models.IntegerField(default=1, verbose_name='Число дней'),
            preserve_default=False,
        ),
    ]
