# Generated by Django 2.0 on 2017-12-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171225_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickssingle',
            name='group_name',
        ),
    ]
