# Generated by Django 2.0 on 2017-12-31 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_table_data_all_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
