# Generated by Django 2.0 on 2017-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171223_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='med',
            name='sexxxx',
        ),
        migrations.AddField(
            model_name='med',
            name='adults',
            field=models.IntegerField(default=30, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med',
            name='sex',
            field=models.CharField(choices=[('муж', 'муж'), ('жен', 'жен')], default='муж', max_length=5, verbose_name='Пол'),
        ),
    ]
