# Generated by Django 2.0 on 2017-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sickssingle_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicks',
            name='group_name',
            field=models.ManyToManyField(to='main.SicksSingle'),
        ),
    ]
