# Generated by Django 2.0 on 2017-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sicks_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='med',
            options={'verbose_name': 'Случай', 'verbose_name_plural': 'Случаи'},
        ),
        migrations.AlterModelOptions(
            name='sicks',
            options={'verbose_name': 'Название группы', 'verbose_name_plural': 'Названия группы'},
        ),
        migrations.AlterModelOptions(
            name='sickssingle',
            options={'verbose_name': 'Код болезни', 'verbose_name_plural': 'Коды болезней'},
        ),
        migrations.AlterModelOptions(
            name='sicksundergroup',
            options={'verbose_name': 'Подгруппы болезни', 'verbose_name_plural': 'Название подгруппы'},
        ),
        migrations.RemoveField(
            model_name='sicks',
            name='group_name',
        ),
        migrations.AddField(
            model_name='sicks',
            name='sicks_code',
            field=models.ManyToManyField(to='main.SicksSingle', verbose_name='Болезни'),
        ),
    ]
