# Generated by Django 2.0 on 2017-12-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171225_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicks',
            name='sicks_code',
        ),
        migrations.AddField(
            model_name='sickssingle',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sicks'),
        ),
    ]
