# Generated by Django 2.0 on 2017-12-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171225_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicksundergroup',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sicks'),
        ),
    ]
