# Generated by Django 2.0 on 2017-12-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171225_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='code',
        ),
    ]
