# Generated by Django 2.0 on 2017-12-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_med_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksSingle', verbose_name='Код болезни'),
        ),
    ]
