# Generated by Django 2.0 on 2017-12-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_med_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='code',
            new_name='code_id',
        ),
    ]
