# Generated by Django 2.0 on 2017-12-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171225_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='code_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Код болезни'),
        ),
        migrations.AlterField(
            model_name='med',
            name='code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksSingle'),
        ),
    ]
