# Generated by Django 2.0 on 2017-12-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171225_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Диапазон возрастов')),
            ],
            options={
                'verbose_name': 'Диапазон возрастов',
                'verbose_name_plural': 'Диапазоны возрастов',
            },
        ),
        migrations.AlterField(
            model_name='med',
            name='code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksSingle', verbose_name='Код болезни'),
        ),
        migrations.AddField(
            model_name='med',
            name='adult_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AgeRange'),
        ),
    ]
