# Generated by Django 2.0 on 2017-12-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171226_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='adult_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AgeRange'),
        ),
        migrations.AlterField(
            model_name='med',
            name='code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SicksSingle', verbose_name='Код болезни'),
        ),
        migrations.AlterField(
            model_name='med',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sicksundergroup',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sicks'),
        ),
    ]
