# Generated by Django 2.0 on 2017-12-26 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_med_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 11, 57, 23, 834219, tzinfo=utc)),
        ),
    ]
