# Generated by Django 2.0 on 2017-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171226_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='med',
            options={'ordering': ['pub_date'], 'verbose_name': 'Случай', 'verbose_name_plural': 'Случаи'},
        ),
        migrations.AlterField(
            model_name='med',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
